## Numpy에서 사용하는 함수들에 대해 araboza

### 🔎 하나의 Array에 적용되는 함수 

In [2]:
import numpy as np

In [11]:
arr1 = np.random.randn(3,5)
arr1

array([[ 0.62468528,  0.42992956, -2.16874814, -0.32378985,  1.02917228],
       [ 1.28302762,  0.51961693,  1.16568353,  1.10789424,  0.90676251],
       [-0.32206233,  0.43218862,  1.3190161 , -1.22794093,  1.36733667]])

In [9]:
# 각 성분의 절대값 계산하기
np.abs(arr1)

array([[0.24144816, 1.92561053, 0.03413883, 0.7514323 , 0.18147978],
       [0.77629816, 0.11221767, 0.36406914, 1.06450705, 0.33087536],
       [0.09562886, 0.83156997, 2.28075356, 2.25099005, 1.05003497]])

In [12]:
# 각 성분의 제곱근 계산하기 (array ** 0.5)
np.sqrt(arr1)

C:\Users\82106\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


array([[0.79037034, 0.65569014,        nan,        nan, 1.01448129],
       [1.13270809, 0.72084459, 1.07966825, 1.05256555, 0.95224078],
       [       nan, 0.65741054, 1.14848426,        nan, 1.16933172]])

In [13]:
# 각 성분의 제곱 계산하기
np.square(arr1)

array([[0.3902317 , 0.18483942, 4.70346849, 0.10483987, 1.05919558],
       [1.64615988, 0.27000175, 1.35881809, 1.22742965, 0.82221824],
       [0.10372414, 0.186787  , 1.73980347, 1.50783893, 1.86960957]])

In [14]:
# 각 성분을 무리수 e의 지수로 삼은 값을 계산하기
np.exp(arr1)

array([[1.86765807, 1.53714924, 0.11432064, 0.72340225, 2.79874829],
       [3.60754549, 1.68138343, 3.20811498, 3.0279755 , 2.47629256],
       [0.72465302, 1.54062568, 3.73974004, 0.29289505, 3.9248835 ]])

In [15]:
# 로그 계산하기
# 자연로그
np.log(arr1)

C:\Users\82106\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until


array([[-0.47050731, -0.8441339 ,         nan,         nan,  0.02875487],
       [ 0.24922261, -0.65466342,  0.15330764,  0.10246114, -0.09787471],
       [        nan, -0.83889316,  0.27688608,         nan,  0.31286481]])

In [16]:
# 상용로그
np.log10(arr1)

C:\Users\82106\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log10
  


array([[-0.20433873, -0.3666027 ,         nan,         nan,  0.01248808],
       [ 0.10823601, -0.28431671,  0.06658066,  0.04449831, -0.04250645],
       [        nan, -0.36432667,  0.1202501 ,         nan,  0.13587546]])

In [17]:
# 밑이 2인 로그
np.log2(arr1)

C:\Users\82106\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log2
  


array([[-0.67879856, -1.21782779,         nan,         nan,  0.0414845 ],
       [ 0.35955223, -0.94447967,  0.22117617,  0.14782017, -0.14120336],
       [        nan, -1.21026701,  0.39946218,         nan,  0.45136851]])

In [18]:
# 각 성분의 부호 계산하기 (양수인 경우 1, 음수인 경우 -1, 0인 경우 0)
np.sign(arr1)

array([[ 1.,  1., -1., -1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [-1.,  1.,  1., -1.,  1.]])

In [19]:
# 각 성분의 소수 첫 번째 자리에서 올림한 값 계산
np.ceil(arr1)

array([[ 1.,  1., -2., -0.,  2.],
       [ 2.,  1.,  2.,  2.,  1.],
       [-0.,  1.,  2., -1.,  2.]])

In [20]:
# 각 성분의 소수 첫 번째 자리에서 내림한 값 계산
np.floor(arr1)

array([[ 0.,  0., -3., -1.,  1.],
       [ 1.,  0.,  1.,  1.,  0.],
       [-1.,  0.,  1., -2.,  1.]])

In [24]:
# 각 성분의 NaN 식별하기
np.isnan(np.log2(arr1))

C:\Users\82106\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log2
  


array([[False, False,  True,  True, False],
       [False, False, False, False, False],
       [ True, False, False,  True, False]])

In [25]:
# 각 성분의 무한대인 경우 식별하기
np.isinf(arr1)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [26]:
# 삼각 함수
np.cos(arr1)

array([[ 0.81114722,  0.90899511, -0.56295085,  0.94803644,  0.51552827],
       [ 0.28381339,  0.86800946,  0.39412243,  0.44654665,  0.61629854],
       [ 0.94858466,  0.9080512 ,  0.24912845,  0.33617767,  0.20205883]])

### 🔎 두 개의 Array에 적용되는 함수 

In [27]:
arr1

array([[ 0.62468528,  0.42992956, -2.16874814, -0.32378985,  1.02917228],
       [ 1.28302762,  0.51961693,  1.16568353,  1.10789424,  0.90676251],
       [-0.32206233,  0.43218862,  1.3190161 , -1.22794093,  1.36733667]])

In [31]:
arr2 = np.random.randn(3,5)
arr2

array([[-1.04046562, -0.44234263,  1.64302474, -0.21095006,  0.08938431],
       [ 1.55322193,  0.02922772,  0.86126364,  0.15805158, -0.79057816],
       [-0.45363803, -0.20204082,  0.15250881,  2.88745894, -0.60867092]])

In [32]:
# 두 개의 array에 대해 동일한 위치의 성분끼리 연산 값 계산하기
# 곱셈
arr1 * arr2

array([[-0.64996356, -0.19017617, -3.56330684,  0.06830349,  0.09199185],
       [ 1.99282664,  0.01518722,  1.00396084,  0.17510444, -0.71686663],
       [ 0.14609972, -0.08731974,  0.20116158, -3.54562902, -0.83225807]])

In [33]:
np.multiply(arr1, arr2)

array([[-0.64996356, -0.19017617, -3.56330684,  0.06830349,  0.09199185],
       [ 1.99282664,  0.01518722,  1.00396084,  0.17510444, -0.71686663],
       [ 0.14609972, -0.08731974,  0.20116158, -3.54562902, -0.83225807]])

`연산에 사용하는 함수들`
- add
- subtract
- multiply
- divide
- miximum
- minimum

In [37]:
np.maximum(arr1, arr2)

array([[ 0.62468528,  0.42992956,  1.64302474, -0.21095006,  1.02917228],
       [ 1.55322193,  0.51961693,  1.16568353,  1.10789424,  0.90676251],
       [-0.32206233,  0.43218862,  1.3190161 ,  2.88745894,  1.36733667]])

### 🔎 통계 함수
array의 합이나 평균을 구할 때,
추가로 axis라는 인자에 대한 값을 지정하여 열 or 행의 합 또는 평균을 구할 수 있음

In [38]:
arr1

array([[ 0.62468528,  0.42992956, -2.16874814, -0.32378985,  1.02917228],
       [ 1.28302762,  0.51961693,  1.16568353,  1.10789424,  0.90676251],
       [-0.32206233,  0.43218862,  1.3190161 , -1.22794093,  1.36733667]])

In [39]:
# 전체 성분의 합을 구함
np.sum(arr1)

6.14277208810671

In [45]:
# 열 간의 합을 계산
np.sum(arr1, axis=0)

array([ 1.58565057,  1.38173511,  0.31595149, -0.44383654,  3.30327145])

In [62]:
# 행 간의 합을 계산
np.sum(arr1, axis=1)

array([-0.40875087,  4.98298483,  1.56853813])

In [63]:
# 평균을 계산
np.mean(arr1)

0.409518139207114

In [64]:
# 열 간의 평균을 계산
np.mean(arr1, axis=0)

array([ 0.52855019,  0.46057837,  0.10531716, -0.14794551,  1.10109048])

In [65]:
# 행 간의 평균을 계산
np.mean(arr1, axis=1)

array([-0.08175017,  0.99659697,  0.31370763])

`전체 성분의 통계값 계산`

|표준편차|분산|최소값|최대값|
|---|---|---|---|
|std|var|min|max|

In [66]:
np.std(arr1)

0.9885811111033306

In [67]:
# 전체 성분의 최소값, 최대값이 위치한 인덱스 반환(argmin, argmax)
np.argmin(arr1)

2

In [68]:
# 열 기준
np.argmin(arr1, axis=0)

array([2, 0, 0, 2, 1], dtype=int64)

In [69]:
# 행 기준
np.argmin(arr1, axis=1)

array([2, 1, 3], dtype=int64)

In [55]:
# 맨 처음 ~ 각 성분까지의 누적 합 또는 누적 곱 (cumsum, cumprod)
np.cumsum(arr1)

array([ 0.62468528,  1.05461484, -1.1141333 , -1.43792315, -0.40875087,
        0.87427675,  1.39389368,  2.55957721,  3.66747145,  4.57423395,
        4.25217163,  4.68436025,  6.00337635,  4.77543542,  6.14277209])

In [70]:
# 열 기준
np.cumsum(arr1, axis=0)

array([[ 0.62468528,  0.42992956, -2.16874814, -0.32378985,  1.02917228],
       [ 1.9077129 ,  0.94954648, -1.00306461,  0.7841044 ,  1.93593478],
       [ 1.58565057,  1.38173511,  0.31595149, -0.44383654,  3.30327145]])

In [73]:
# 행 기준
np.cumsum(arr1, axis=1)

array([[ 0.62468528,  1.05461484, -1.1141333 , -1.43792315, -0.40875087],
       [ 1.28302762,  1.80264455,  2.96832808,  4.07622232,  4.98298483],
       [-0.32206233,  0.11012629,  1.42914239,  0.20120146,  1.56853813]])

### 🔎 기타 함수

In [74]:
arr1

array([[ 0.62468528,  0.42992956, -2.16874814, -0.32378985,  1.02917228],
       [ 1.28302762,  0.51961693,  1.16568353,  1.10789424,  0.90676251],
       [-0.32206233,  0.43218862,  1.3190161 , -1.22794093,  1.36733667]])

In [79]:
# 오름차순 정렬
# default로 행 기준으로 되네!
np.sort(arr1)

array([[-2.16874814, -0.32378985,  0.42992956,  0.62468528,  1.02917228],
       [ 0.51961693,  0.90676251,  1.10789424,  1.16568353,  1.28302762],
       [-1.22794093, -0.32206233,  0.43218862,  1.3190161 ,  1.36733667]])

In [80]:
# 내림차순 정렬
np.sort(arr1)[::-1] # <- 그냥 역순 슬라이싱

array([[-1.22794093, -0.32206233,  0.43218862,  1.3190161 ,  1.36733667],
       [ 0.51961693,  0.90676251,  1.10789424,  1.16568353,  1.28302762],
       [-2.16874814, -0.32378985,  0.42992956,  0.62468528,  1.02917228]])

In [81]:
# 열 방향으로 오름차순 정렬
np.sort(arr1, axis=0)

array([[-0.32206233,  0.42992956, -2.16874814, -1.22794093,  0.90676251],
       [ 0.62468528,  0.43218862,  1.16568353, -0.32378985,  1.02917228],
       [ 1.28302762,  0.51961693,  1.3190161 ,  1.10789424,  1.36733667]])

In [82]:
# 후하후하 끝끝